# Generated by Django 4.0.3 on 2022-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_home_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.CharField(default='city', max_length=100),
        ),
    ]
